inventory/app/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path('product/<int:gtin>/delete', views.ProductDeleteView.as_view(), name="delete"),
    path('product/<int:gtin>/<int:pk>/delete', views.ProductExpirationDeleteView.as_view(), name="delete_date"),
    path('product/<int:gtin>', views.ProductView.as_view(), name="view"),
    url('add', views.ProductAddView.as_view(), name="add"),
    url('', views.IndexView.as_view(), name="index")
]

inventory/inventory/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

if settings.DEBUG:
    from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include("app.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventory/app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class ProductExpiration(models.Model):
    product = models.ForeignKey("Product",
                                related_name="expirations",
                                on_delete=models.CASCADE)
    date = models.DateField(verbose_name="Product expiration date")

    @property
    def delete_url(self):
        return reverse('app:delete_date', kwargs={'gtin': self.product.barcode, 'pk': self.pk})


class Product(models.Model):
    name = models.CharField(verbose_name="Product name", max_length=256)
    barcode = models.IntegerField(verbose_name="Product GTIN", unique=True)

    @property
    def shortest_expiration_date(self):
        return self.expirations.order_by('date').first()

    @property
    def url(self):
        return reverse('app:view', kwargs={'gtin': self.barcode})

    @property
    def delete_url(self):
        return reverse('app:delete', kwargs={'gtin': self.barcode})

inventory/app/forms.py
from django import forms


class ProductAddForm(forms.Form):
    name = forms.CharField(label="product_name", max_length=256)
    barcode = forms.IntegerField(label="product_barcode", min_value=0)
    expiration_date = forms.DateField(label="expiration_date", widget=forms.DateInput(attrs={'type': 'date'}))

inventory/app/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, View
from django.views.generic.edit import FormView
from .models import Product, ProductExpiration
from .forms import ProductAddForm


# Create your views here.

class IndexView(ListView):
    template_name = "app/index.html"
    model = Product


class ProductAddView(FormView):
    template_name = "app/add.html"
    form_class = ProductAddForm
    success_url = "/"

    # If form is valid
    def form_valid(self, form):
        product = Product.objects.filter(barcode=form.cleaned_data["barcode"])
        if product.exists():
            product = product.first()
            if product.name is not form.cleaned_data["name"]:
                # Update the name of the product
                product.name = form.cleaned_data["name"]
                product.save()
        else:
            # Product does not exist, we create it
            product = Product(name=form.cleaned_data["name"],
                              barcode=form.cleaned_data["barcode"])
            product.save()
        ProductExpiration(product=product, date=form.cleaned_data["expiration_date"]).save()

        return super(ProductAddView, self).form_valid(form)


class ProductView(ListView):
    template_name = "app/product.html"
    model = Product

    def get(self, request, gtin, *args, **kwargs):
        self.object = get_object_or_404(self.model, barcode=gtin)
        return super(ProductView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        context['product'] = self.object
        return context

    def get_queryset(self):
        return self.object.expirations.order_by("date").all()


class ProductDeleteView(View):
    redirect_url = 'app:index'
    model = Product

    def get(self, request, gtin):
        product = get_object_or_404(self.model, barcode=gtin)
        product.delete()
        return redirect(self.redirect_url)


class ProductExpirationDeleteView(View):
    redirect_url = 'app:index'
    model = ProductExpiration

    def get(self, request, gtin, pk):
        product_expir = get_object_or_404(self.model, product__barcode=gtin, pk=pk)
        product = product_expir.product
        product_expir.delete()

        if product.expirations.count() == 0:
            # No stock, so we can delete the product
            product.delete()

        return redirect(self.redirect_url)

inventory/templates/app/add.html
{% extends 'app/base.html' %}
{% block content %}
        <div>
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {{ form.name.errors }}
                    <label for="{{ form.name.id_for_label }}">Product name:</label>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    {{ form.barcode.errors }}
                    <label for="{{ form.barcode.id_for_label }}">Product GTIN:</label>
                    {{ form.barcode }}
                </div>
                <div class="form-group">
                    {{ form.expiration_date.errors }}
                    <label for="{{ form.expiration_date.id_for_label }}">Product expiration date:</label>
                    {{ form.expiration_date }}
                </div>
                <button type="submit" class="btn btn-primary">Add</button>
            </form>
        </div>
{% endblock %}

inventory/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>My Shop</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "css/style.css" %}">
    </head>
    <body>
        <header>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h1 class="align-center">My shop</h1>
                    </div>
                    <div class="col">
                        <div class="navbar">
                            <nav id="navbar-nav">
                                <a href="{% url "app:index" %}">Home</a>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <main class="container">
            <br>
            {% block content %}
            {% endblock %}
        </main>
        <footer class="align-center">
            <div class="row">
                <div class="col">
                    Coded by Cédric FARINAZZO in June 2020
                </div>
                <div class="col">
                    <a href="https://gitlab.com/cedricfarinazzo/cbplus-inventory-app"><img class="logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/GitLab_logo.svg/1200px-GitLab_logo.svg.png" alt="gitlab logo"/></a>
                </div>
            </div>
        </footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static "js/app.js" %}"></script>
    </body>
</html>

inventory/templates/app/index.html
{% extends 'app/base.html' %}
{% block content %}
        <div>
            <div class="container">
                <div class="row justify-content-md-center">
                    <div class="col">
                        <h2>Product list</h2>
                    </div>
                    <div class="col col-lg-2">
                        <a class="btn btn-primary" href="{% url "app:add" %}">Add a product</a>
                    </div>
                </div>
            </div>
            {% if object_list %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Product name</th>
                            <th>Shortest expiration date</th>
                            <th>GTIN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in object_list %}
                            <tr>
                                <th>{{ product.name }}</th>
                                <th>{{ product.shortest_expiration_date.date|date }}</th>
                                <th><a href="{{ product.url }}">{{ product.barcode }}</a></th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No products yet.</p>
            {% endif %}
        </div>
{% endblock %}

inventory/templates/app/product.html
{% extends 'app/base.html' %}
{% block content %}
        <div>
            <h2>Product detail</h2>
            <div>
                Name: {{ product.name }}
                <br>
                GTIN: {{ product.barcode }}
            </div>
            <div>
                <a class="btn btn-primary" href="{{ product.delete_url }}">Delete</a>
            </div>
            <br>
            <div>
                <h3>Stock list</h3>
                <div>
                    <ul>
                        {% for d in object_list %}
                            <li>
                                <div class="row">
                                    <div class="col">
                                        {{ d.date|date }}
                                    </div>
                                    <div class="col">
                                        <a class="btn btn-primary" href="{{ d.delete_url }}">Delete</a>
                                    </div>
                                </div>
                            </li>
                        {% empty %}
                            <li>No product yet.</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
{% endblock %}